include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    use_build_context_synchronously: true
    sort_constructors_first: false
    one_member_abstracts: false
    avoid_dynamic_calls: false
    # Disable some very noisy rules for now
    directives_ordering: false
    always_put_required_named_parameters_first: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-raw-types: false
    strict-casts: false
    strict-inference: false
