package http

// The registered route table is a checked-in list (lane C1, section 4).
//
// A route appears on the public surface the moment it is registered, and the
// fence is the only thing between a registered route and a caller. So adding
// or removing a route must be a decision someone makes on purpose, in review:
// this test fails until testdata/routes.txt is edited to match, and the diff of
// that file is the review.
//
//	go test ./internal/http/ -run TestRouteInventory -update-routes
//
// rewrites the list from the table; read the diff before keeping it.
//
// The table is built the way cmd/server builds it with PAYMENTS_ALLOW_STUB
// unset (production): RegisterRoutes then RegisterP0Routes. The stub confirm
// route is checked separately, because it exists only on a stub stack.

import (
	"flag"
	"net/http"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"
)

var updateRoutes = flag.Bool("update-routes", false, "rewrite testdata/routes.txt from the registered route table")

const routesFile = "testdata/routes.txt"

func registeredRouteSet(stub bool) []string {
	r := gin.New()
	h := (&Handler{}).WithStubSettlement(stub)
	h.RegisterRoutes(r)
	h.RegisterP0Routes(r)
	out := make([]string, 0, len(r.Routes()))
	for _, ri := range r.Routes() {
		out = append(out, ri.Method+" "+ri.Path)
	}
	sort.Strings(out)
	return out
}

func readRouteList(t *testing.T) []string {
	t.Helper()
	raw, err := os.ReadFile(routesFile)
	if err != nil {
		t.Fatalf("%s: %v (run with -update-routes to write it)", routesFile, err)
	}
	var out []string
	for _, line := range strings.Split(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	return out
}

func TestRouteInventoryMatchesTheCheckedInList(t *testing.T) {
	got := registeredRouteSet(false)
	if *updateRoutes {
		body := "# The commerce-service route table (production: PAYMENTS_ALLOW_STUB unset).\n" +
			"# Generated by `go test ./internal/http/ -run TestRouteInventory -update-routes`.\n" +
			"# A registered route is not necessarily reachable: the fence (handler_p0.go) 404s\n" +
			"# fenced prefixes and routes ahead of routing. See routes_inventory_test.go.\n" +
			strings.Join(got, "\n") + "\n"
		if err := os.WriteFile(routesFile, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want := readRouteList(t)
	gotSet, wantSet := map[string]bool{}, map[string]bool{}
	for _, r := range got {
		gotSet[r] = true
	}
	for _, r := range want {
		wantSet[r] = true
	}
	for _, r := range got {
		if !wantSet[r] {
			t.Errorf("route %q is registered but not in %s — add it on purpose (-update-routes) or remove it", r, routesFile)
		}
	}
	for _, r := range want {
		if !gotSet[r] {
			t.Errorf("route %q is in %s but no longer registered — delete the line on purpose (-update-routes)", r, routesFile)
		}
	}
	t.Logf("%d registered routes", len(got))
}

// The two facts the MStore/MSeller contract depends on, pinned by name so the
// list cannot be regenerated past them unnoticed.
func TestRouteInventoryPinsTheP0Surface(t *testing.T) {
	list := map[string]bool{}
	for _, r := range readRouteList(t) {
		list[r] = true
	}
	for _, must := range []string{
		"GET /v1/commerce/orders/:orderId/payment",        // the three-state read
		"GET /v1/commerce/orders/:orderId/payment/status", // the legacy read, kept for the shipped Android build
		"POST /v1/commerce/orders/:orderId/payment/intent",
		"POST /v1/commerce/v2/orders/checkout",
		"POST /v1/commerce/checkout/quote",
	} {
		if !list[must] {
			t.Errorf("%q must be registered", must)
		}
	}
	for _, mustNot := range []string{
		"POST /v1/commerce/orders/checkout",                 // the v1 checkout: prepaid-unsafe, gone
		"POST /v1/commerce/orders/:orderId/payment/confirm", // stub stacks only
	} {
		if list[mustNot] {
			t.Errorf("%q must NOT be registered in production", mustNot)
		}
	}
}

// With PAYMENTS_ALLOW_STUB the table gains exactly the stub confirm route.
func TestStubFlagAddsOnlyTheConfirmRoute(t *testing.T) {
	prod := map[string]bool{}
	for _, r := range registeredRouteSet(false) {
		prod[r] = true
	}
	var added []string
	for _, r := range registeredRouteSet(true) {
		if !prod[r] {
			added = append(added, r)
		}
	}
	if len(added) != 1 || added[0] != http.MethodPost+" /v1/commerce/orders/:orderId/payment/confirm" {
		t.Fatalf("the stub flag added %v, want exactly the confirm route", added)
	}
}
