-- 022: drop payout_batches and payout_statements (plan Phase 3B cleanup).
--
-- The batch and statement code was removed in Phase 3B: nothing ever
-- wrote a batch, and the statement that this table would have served was
-- never generated by anything. The creator-facing record is the period
-- statement under /creator-fund/statements. With the code gone the
-- tables go too. payout_requests.batch_id references payout_batches and
-- has to be dropped first.
ALTER TABLE payout_requests DROP COLUMN IF EXISTS batch_id;
DROP TABLE IF EXISTS payout_statements;
DROP TABLE IF EXISTS payout_batches;
