package servicetoken

// Code generated by the fixture generator against
// Architecture/shared/servicetoken (the SHARED package) — DO NOT EDIT by hand.
//
// A token minted by the shared package's Signer from a deterministic seed
// (sha256 of a fixed string, so the key pair is a public test vector, not a
// secret). The local verifier must accept it byte-for-byte: same JOSE
// header, same claim names, same base64url framing, same Ed25519 signature
// input. If the shared package's wire format ever changes, this fixture is
// regenerated and the test here fails until the local verifier follows.

const (
	sharedFixtureIssuer = "admin-service"
	sharedFixtureKID    = "fixture-1"
	sharedFixtureAud    = "identity"
	sharedFixtureScope  = "platform:roles.manage"
	sharedFixtureActor  = "7b1e4c1a-2f3d-4e5f-8a9b-0c1d2e3f4a5b"
	sharedFixtureJTI    = "a6gdetN8-fB7kIxZ3aBZ9Q"
	sharedFixtureIAT    = int64(1789655817)
	sharedFixturePubB64 = "SrA+7UXf/xNl6zrqPPstMMROQFhF4CqhikWun9iQLIk="
	sharedFixtureToken  = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImZpeHR1cmUtMSJ9.eyJpc3MiOiJhZG1pbi1zZXJ2aWNlIiwic3ViIjoiYWRtaW4tY29uc29sZSIsImF1ZCI6ImlkZW50aXR5IiwiZXhwIjoxNzg5NjU1ODc3LCJuYmYiOjE3ODk2NTU3ODcsImlhdCI6MTc4OTY1NTgxNywianRpIjoiYTZnZGV0TjgtZkI3a0l4WjNhQlo5USIsInNjb3BlIjpbInBsYXRmb3JtOnJvbGVzLm1hbmFnZSJdLCJyZWZfdHlwZXMiOm51bGwsImFjdCI6IjdiMWU0YzFhLTJmM2QtNGU1Zi04YTliLTBjMWQyZTNmNGE1YiJ9.BhhBCZjNaOQhE4w2oLeiee6D3PVaXHarKLq3TjgMZxaueUTk5PwsDROYrKkWfd3tt5q5CuHUqet8UHzZwzdlDA"
)
