package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Outputs lists what an apply wrote, for the checklist.
type Outputs struct {
	SecretFiles []string
	Removed     []string // stale payloads deleted (their secret needs no push)
	PushScript  string
	RolesSQL    string
	PublicFiles []string
}

// WriteOutputs writes the emitted payloads and helper files under dir.
// Only secrets that need a push get a payload file; a payload left over from
// an earlier apply for a secret that now needs nothing is removed, so no
// value sits on disk longer than it has to. Nothing here is printed; the
// caller prints paths only.
func WriteOutputs(dir string, m *Manifest, p *Plan, region string, now time.Time) (Outputs, error) {
	var out Outputs
	secretsDir := filepath.Join(dir, "secrets")
	if err := os.MkdirAll(secretsDir, 0o700); err != nil {
		return out, err
	}
	for _, s := range p.Secrets {
		path := filepath.Join(secretsDir, s.Name+".json")
		if !s.Changed() {
			if err := os.Remove(path); err == nil {
				out.Removed = append(out.Removed, path)
			} else if !errors.Is(err, os.ErrNotExist) {
				return out, err
			}
			continue
		}
		b, err := json.MarshalIndent(s.Payload(), "", "  ")
		if err != nil {
			return out, err
		}
		if err := writePrivate(path, append(b, '\n')); err != nil {
			return out, err
		}
		out.SecretFiles = append(out.SecretFiles, path)
	}

	push := filepath.Join(dir, "put-secret-values.sh")
	if err := writePrivate(push, []byte(pushScript(m.Env, p, region, now))); err != nil {
		return out, err
	}
	if err := os.Chmod(push, 0o700); err != nil {
		return out, err
	}
	out.PushScript = push

	sqlPath := filepath.Join(dir, "roles.sql")
	if len(p.Roles) > 0 && len(p.RolePasswords) > 0 {
		if err := writePrivate(sqlPath, []byte(rolesSQL(p, now))); err != nil {
			return out, err
		}
		out.RolesSQL = sqlPath
	}

	if len(p.PublicHalves) > 0 {
		pubDir := filepath.Join(dir, "public")
		if err := os.MkdirAll(pubDir, 0o700); err != nil {
			return out, err
		}
		names := make([]string, 0, len(p.PublicHalves))
		for n := range p.PublicHalves {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			pair := p.PublicHalves[n]
			ext := ".pub.b64"
			body := pair.Public + "\n"
			if strings.HasPrefix(pair.Public, "-----BEGIN") {
				ext = ".pub.pem"
				body = pair.Public
			}
			path := filepath.Join(pubDir, n+ext)
			if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
				return out, err
			}
			out.PublicFiles = append(out.PublicFiles, path)
		}
	}
	return out, nil
}

// pushScript is the exact aws CLI sequence for the lead. The value travels
// as file:// (never on the command line, so never in `ps` or shell history),
// and each payload is deleted as soon as its put succeeds.
func pushScript(env string, p *Plan, region string, now time.Time) string {
	var b strings.Builder
	fmt.Fprintf(&b, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&b, "# Generated by tools/prodsecrets on %s.\n", now.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "# Pushes secrets/<name>.json into the EMPTY-SHELL secrets Terraform created,\n")
	fmt.Fprintf(&b, "# then deletes each payload. Review `prodsecrets --plan` first. Nothing is echoed.\n")
	fmt.Fprintf(&b, "set -euo pipefail\n")
	// pwd -W gives a C:/ path under Git Bash, which the Windows aws.exe needs
	// inside file://; elsewhere it fails and plain pwd is used.
	fmt.Fprintf(&b, "DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && (pwd -W 2>/dev/null || pwd))\"\n")
	fmt.Fprintf(&b, "REGION=\"${AWS_REGION:-%s}\"\n", region)
	fmt.Fprintf(&b, "put() {\n")
	fmt.Fprintf(&b, "  local id=\"$1\" file=\"$DIR/secrets/$2.json\"\n")
	fmt.Fprintf(&b, "  if [[ ! -f \"$file\" ]]; then echo \"skip $id (payload already pushed)\"; return; fi\n")
	fmt.Fprintf(&b, "  aws secretsmanager put-secret-value --region \"$REGION\" --secret-id \"$id\" \\\n")
	fmt.Fprintf(&b, "    --secret-string \"file://$file\" --query VersionId --output text >/dev/null\n")
	fmt.Fprintf(&b, "  rm -f \"$file\"\n")
	fmt.Fprintf(&b, "  echo \"pushed $id\"\n")
	fmt.Fprintf(&b, "}\n\n")
	n := 0
	for _, s := range p.Secrets {
		if s.Changed() {
			fmt.Fprintf(&b, "put %s %s\n", s.FullName, s.Name)
			n++
		} else {
			fmt.Fprintf(&b, "# %s: nothing to push this run\n", s.FullName)
		}
	}
	fmt.Fprintf(&b, "\necho \"%d secret(s) pushed. Next: %s plan  (expect: keep everywhere)\"\n", n, wrapperCmd(env))
	return b.String()
}

// rolesSQL is an idempotent psql script: one NOLOGIN owner group per
// database, one LOGIN role per service that joins the group and assumes it
// per database, so every member can migrate and read tables any other member
// created. Run as the Aurora master user; re-running converges (passwords are
// always set to the value in the matching DSN).
func rolesSQL(p *Plan, now time.Time) string {
	byDB := map[string][]string{}
	roles := map[string]bool{}
	for _, g := range p.Roles {
		byDB[g.Database] = append(byDB[g.Database], g.Role)
		roles[g.Role] = true
	}
	dbs := make([]string, 0, len(byDB))
	for db := range byDB {
		dbs = append(dbs, db)
	}
	sort.Strings(dbs)
	roleNames := make([]string, 0, len(roles))
	for r := range roles {
		roleNames = append(roleNames, r)
	}
	sort.Strings(roleNames)

	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by tools/prodsecrets on %s. CONTAINS PASSWORDS: deleted by\n", now.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "-- `scripts/prodsecrets.sh roles`, which runs it inside the cluster (Aurora is\n")
	fmt.Fprintf(&b, "-- private) as the master user from the aurora-master Secret that Terraform's\n")
	fmt.Fprintf(&b, "-- aurora-bootstrap module mirrors. Re-running is safe. The five databases\n")
	fmt.Fprintf(&b, "-- and their extensions already exist (aurora-bootstrap job).\n\n")
	fmt.Fprintf(&b, "\\set ON_ERROR_STOP on\n\n")
	for _, role := range roleNames {
		pw, ok := p.RolePasswords[role]
		if !ok {
			continue
		}
		if p.RotatedRoles[role] {
			fmt.Fprintf(&b, "-- %s: password ROTATED this run\n", role)
		}
		fmt.Fprintf(&b, "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '%s') THEN CREATE ROLE %s LOGIN; END IF; END $$;\n", role, role)
		fmt.Fprintf(&b, "ALTER ROLE %s WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD %s;\n\n", role, sqlLiteral(pw))
	}
	for _, db := range dbs {
		owner := db + "_owner"
		members := byDB[db]
		sort.Strings(members)
		fmt.Fprintf(&b, "-- database %s: owner group %s; members %s\n", db, owner, strings.Join(members, ", "))
		fmt.Fprintf(&b, "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '%s') THEN CREATE ROLE %s NOLOGIN; END IF; END $$;\n", owner, owner)
		fmt.Fprintf(&b, "GRANT %s TO CURRENT_USER;\n", owner)
		fmt.Fprintf(&b, "ALTER DATABASE %s OWNER TO %s;\n", db, owner)
		fmt.Fprintf(&b, "REVOKE CONNECT ON DATABASE %s FROM PUBLIC;\n", db)
		for _, role := range members {
			fmt.Fprintf(&b, "GRANT CONNECT ON DATABASE %s TO %s;\n", db, role)
			fmt.Fprintf(&b, "GRANT %s TO %s;\n", owner, role)
			fmt.Fprintf(&b, "ALTER ROLE %s IN DATABASE %s SET role = '%s';\n", role, db, owner)
		}
		fmt.Fprintf(&b, "\\connect %s\n", db)
		fmt.Fprintf(&b, "ALTER SCHEMA public OWNER TO %s;\n", owner)
		fmt.Fprintf(&b, "GRANT ALL ON ALL TABLES IN SCHEMA public TO %s;\n", owner)
		fmt.Fprintf(&b, "GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO %s;\n", owner)
		fmt.Fprintf(&b, "\\connect postgres\n\n")
	}
	return b.String()
}

func sqlLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
