#!/usr/bin/env bash
# gen-azure-values.sh — generate the Azure per-cloud Helm values from the
# AWS ones, the same way new-zone.sh scaffolds zones. Reads every
# deploy/services/<svc>/values-<env>.yaml and deploy/web/<zone>/values-<env>.yaml
# and writes a sibling values-azure-<env>.yaml with the cloud-specific bits
# swapped:
#
#   image.repository      ECR  → ACR  (atpost<env>.azurecr.io/atpost/<name>)
#   serviceAccount        drop irsaRoleArn (Azure app pods get creds via ESO,
#                         not pod identity — only ESO needs Workload Identity)
#   externalSecret        secretStoreName → azure-key-vault;
#                         remoteKey  atpost/<env>/<svc> → atpost-<env>-<svc>
#                         (Key Vault secret names allow only [0-9a-zA-Z-])
#   ingress               className alb → nginx; alb.* annotations → nginx;
#                         drop the ACM certificate-arn (TLS terminates at
#                         Azure Front Door)
#
# Everything else (env, resources, hpa, inter-service *.svc.cluster.local
# URLs) is identical across clouds and copied verbatim. The chart itself is
# never touched — only these values differ. Re-run after editing any AWS
# values file; the output is GENERATED, never hand-edited.
#
# Usage: scripts/gen-azure-values.sh [staging|prod|all]   (default: all)
set -euo pipefail

cd "$(dirname "$0")/.."
ENVS="${1:-all}"
[ "$ENVS" = "all" ] && ENVS="staging prod"

python3 - "$ENVS" <<'PY'
import sys, glob, os, re, yaml

envs = sys.argv[1].split()

def acr_registry(env):
    # Matches infra/azure/modules/acr name = atpost<env> (no dashes allowed
    # in ACR names). Override here if you renamed the registries.
    return f"atpost{env}.azurecr.io"

def transform(doc, env, kind, name):
    # image → ACR
    img = doc.get("image")
    if isinstance(img, dict) and img.get("repository"):
        repo_name = img["repository"].rsplit("/", 1)[-1]  # e.g. atpost/api-gateway → api-gateway
        img["repository"] = f"{acr_registry(env)}/atpost/{repo_name}"

    # serviceAccount → drop IRSA (no Azure pod identity for app pods)
    sa = doc.get("serviceAccount")
    if isinstance(sa, dict):
        sa.pop("irsaRoleArn", None)
        if not sa:
            doc.pop("serviceAccount", None)

    # externalSecret → azure-key-vault + dashed remoteKey
    es = doc.get("externalSecret")
    if isinstance(es, dict) and es.get("enabled"):
        es["secretStoreName"] = "azure-key-vault"
        if es.get("remoteKey"):
            es["remoteKey"] = es["remoteKey"].replace("/", "-")

    # ingress → nginx, drop ALB-isms
    ing = doc.get("ingress")
    if isinstance(ing, dict) and ing.get("enabled"):
        ing["className"] = "nginx"
        ann = {
            "nginx.ingress.kubernetes.io/ssl-redirect": "true",
            # media/uploads can be large; lift the default 1m body cap.
            "nginx.ingress.kubernetes.io/proxy-body-size": "50m",
        }
        ing["annotations"] = ann
        # TLS is terminated at Front Door; no per-Ingress cert.
        ing.pop("tls", None)
    return doc

def process(pattern, kind):
    n = 0
    for env in envs:
        for src in sorted(glob.glob(pattern.format(env=env))):
            with open(src) as f:
                doc = yaml.safe_load(f) or {}
            name = os.path.basename(os.path.dirname(src))
            doc = transform(doc, env, kind, name)
            dst = src.replace(f"values-{env}.yaml", f"values-azure-{env}.yaml")
            header = (
                f"# GENERATED by scripts/gen-azure-values.sh from {os.path.basename(src)} — DO NOT hand-edit.\n"
                f"# Azure ({env}) overlay of the {kind} '{name}': ACR image, nginx ingress,\n"
                f"# azure-key-vault ClusterSecretStore. Re-run the script after editing the AWS values.\n"
            )
            with open(dst, "w") as f:
                f.write(header)
                yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False)
            n += 1
            print(f"  {dst}")
    return n

print("services:")
s = process("deploy/services/*/values-{env}.yaml", "service")
print("web zones:")
w = process("deploy/web/*/values-{env}.yaml", "web zone")
print(f"done — {s} service + {w} web files generated.")
PY
