package http

import (
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"net/http"

	"github.com/atpost/monetization-service/internal/service"
	"github.com/atpost/shared/api"
	"github.com/gin-gonic/gin"
)

// The /payout-statements routes and their handlers were removed in plan
// Phase 3B: the statement they served was never generated by anything,
// and the period statements under /creator-fund/statements are the
// creator-facing record now.

// ---------------------------------------------------------------------------
// Payout Webhook (plan Phase 4C)
// ---------------------------------------------------------------------------

// HandlePayoutWebhook takes RazorpayX's callback about a payout.
//
// While payouts are disabled (Phase 3C), or enabled but the rail is not
// configured (no client), the raw event is stored in the audit log and
// answered 202: nothing is acted on, nothing is lost. Otherwise the
// service verifies the raw-body signature, deduplicates on the event id,
// and converges the request row; the reply says which of those happened.
// A bad signature is 401, a missing event id 400; the provider retries
// neither, which is right — a retry would carry the same defect.
func (h *Handler) HandlePayoutWebhook(c *gin.Context) {
	raw, err := io.ReadAll(io.LimitReader(c.Request.Body, 1<<20))
	if err != nil {
		api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusBadRequest, "INVALID_REQUEST", "unreadable body", nil)
		return
	}
	store := func(reason string) {
		if !json.Valid(raw) {
			api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusBadRequest, "INVALID_REQUEST", "body is not JSON", nil)
			return
		}
		if err := h.svc.StorePayoutWebhookEvent(c.Request.Context(), raw, c.ClientIP(), reason); err != nil {
			api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusInternalServerError, "INTERNAL_ERROR", err.Error(), nil)
			return
		}
		slog.Warn("payout webhook stored, not processed", "reason", reason, "bytes", len(raw))
		api.JSON(c.Writer, http.StatusAccepted, map[string]string{"status": "stored", "reason": reason}, nil)
	}
	if !h.payoutsEnabled {
		store("payouts_disabled")
		return
	}
	if !h.svc.PayoutRailEnabled() {
		store("rail_not_configured")
		return
	}

	res, err := h.svc.HandleProviderWebhook(c.Request.Context(), c.Request.Header, raw)
	if err != nil {
		switch {
		case errors.Is(err, service.ErrWebhookSignature):
			api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusUnauthorized, "WEBHOOK_SIGNATURE_INVALID", "signature does not verify", nil)
		case errors.Is(err, service.ErrWebhookEventID):
			api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusBadRequest, "WEBHOOK_EVENT_ID_MISSING", "X-Razorpay-Event-Id is required", nil)
		case errors.Is(err, service.ErrPayoutRailNotConfigured):
			store("rail_not_configured")
		default:
			// A processing failure: the event is stored and unconsumed; a
			// 5xx makes the provider redeliver, which lands as a replay,
			// so the operator has to act on the stored event. Say so.
			slog.Error("payout webhook processing failed", "event_id", res.EventID, "error", err)
			api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusInternalServerError, "INTERNAL_ERROR", "event stored; processing failed", nil)
		}
		return
	}
	api.JSON(c.Writer, http.StatusOK, res, nil)
}
