package http

import (
	"encoding/json"
	"io"
	"log/slog"
	"net/http"

	"github.com/atpost/shared/api"
	"github.com/gin-gonic/gin"
)

// The /payout-statements routes and their handlers were removed in plan
// Phase 3B: the statement they served was never generated by anything,
// and the period statements under /creator-fund/statements are the
// creator-facing record now.

// ---------------------------------------------------------------------------
// Payout Webhook
// ---------------------------------------------------------------------------

type PayoutWebhookRequest struct {
	ProviderReference string `json:"provider_reference" binding:"required"`
	Status            string `json:"status" binding:"required"`
	FailureReason     string `json:"failure_reason"`
}

// HandlePayoutWebhook takes the provider's callback about a payout.
//
// While payouts are disabled (plan Phase 3C) the event is stored and
// answered 202: nothing is acted on, nothing is lost, and Phase 4's
// reconciler can find it in the audit log. Signature verification is
// Phase 4C's, with the RazorpayX client.
func (h *Handler) HandlePayoutWebhook(c *gin.Context) {
	raw, err := io.ReadAll(io.LimitReader(c.Request.Body, 1<<20))
	if err != nil {
		api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusBadRequest, "INVALID_REQUEST", "unreadable body", nil)
		return
	}
	if !h.payoutsEnabled {
		if !json.Valid(raw) {
			api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusBadRequest, "INVALID_REQUEST", "body is not JSON", nil)
			return
		}
		if err := h.svc.StorePayoutWebhookEvent(c.Request.Context(), raw, c.ClientIP()); err != nil {
			api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusInternalServerError, "INTERNAL_ERROR", err.Error(), nil)
			return
		}
		slog.Warn("payout webhook stored, not processed: payouts are disabled", "bytes", len(raw))
		api.JSON(c.Writer, http.StatusAccepted, map[string]string{"status": "stored", "reason": "PAYOUTS_NOT_ENABLED"}, nil)
		return
	}

	var req PayoutWebhookRequest
	if err := json.Unmarshal(raw, &req); err != nil || req.ProviderReference == "" || req.Status == "" {
		api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusBadRequest, "INVALID_REQUEST", "provider_reference and status are required", nil)
		return
	}

	if err := h.svc.HandlePayoutWebhook(c.Request.Context(), req.ProviderReference, req.Status, req.FailureReason); err != nil {
		if err.Error() == "PAYOUT_NOT_FOUND" {
			api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusNotFound, "NOT_FOUND", "Payout not found for provider reference", nil)
			return
		}
		api.ErrorWithContext(c.Request.Context(), c.Writer, http.StatusInternalServerError, "INTERNAL_ERROR", err.Error(), nil)
		return
	}

	api.JSON(c.Writer, http.StatusOK, map[string]string{"status": "processed"}, nil)
}
